# Used for development
version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - mysqltemporal:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_PASSWORD: examplepass
      MYSQL_USER: admin
      MYSQL_DATABASE: example
      MYSQL_PORT: 3307
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']


volumes:
  mysqltemporal:

